version: "1.1"

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: contentcoach-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: content_coach

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: contentcoach-redis
    restart: unless-stopped

    volumes:
      - redis_data:/data

  backend:
    image: 090082365566.dkr.ecr.us-east-1.amazonaws.com/content-coach-backend-repo:latest
    container_name: contentcoach-backend
    restart: unless-stopped

    environment:
      ENV: production
      AWS_SECRET_NAME: content-coach-ai-development-secrets
      AWS_REGION: us-east-1
      DATABASE_URL: postgresql://postgres:postgres@db:5432/content_coach

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
