# Post-structure template definitions, keyed by id. These ids are canonical —
# frontend/src/data/templates.js's ids must match exactly, since the frontend
# only ever sends an id (never the JSON itself) via /api/ai/resume's
# template_id field; the backend is the only place the full structure lives.
TEMPLATE_DEFINITIONS: dict[str, dict] = {
    "clean_paragraphs": {
        "id": "clean_paragraphs",
        "name": "Clean Paragraphs",
        "purpose": "Clear, professional posts with a natural paragraph flow.",
        "structure": ["Hook", "Context", "Main Idea", "Supporting Ideas", "Conclusion"],
        "format": {
            "paragraphs": "short",
            "spacing": "generous",
            "bullets": False,
            "emojis": False,
            "formatting": "minimal",
        },
        "opening": "Start with a strong, relevant hook.",
        "body": "Keep one main idea per paragraph and create a natural progression.",
        "ending": "Finish with a thoughtful, conclusive statement.",
        "avoid": ["Long paragraphs", "Excessive formatting", "Generic filler"],
    },
    "storytelling": {
        "id": "storytelling",
        "name": "Storytelling",
        "purpose": "Turn an idea or experience into a compelling narrative with a clear lesson.",
        "structure": ["Hook", "Setup", "Experience", "Turning Point", "Lesson", "Closing"],
        "format": {
            "paragraphs": "short",
            "spacing": "generous",
            "bullets": False,
            "emojis": False,
            "formatting": "minimal",
        },
        "opening": "Create curiosity with a strong hook.",
        "body": "Build the situation, experience, tension, and turning point naturally.",
        "ending": "Extract a meaningful lesson and close with an earned insight.",
        "avoid": ["Fictional details", "Over-dramatization", "Forced lessons", "Generic engagement bait"],
    },
    "bullet_breakdown": {
        "id": "bullet_breakdown",
        "name": "Bullet Breakdown",
        "purpose": "Make information highly scannable using concise, distinct bullet points.",
        "structure": ["Hook", "Context", "Key Points", "Takeaway"],
        "format": {
            "paragraphs": "short",
            "spacing": "generous",
            "bullets": True,
            "bullet_count": "3-6",
            "emojis": False,
            "formatting": "minimal",
        },
        "opening": "Introduce the topic with a concise hook and context.",
        "body": "Present each distinct idea as a concise, consistent bullet.",
        "ending": "Finish with a clear takeaway after the bullets.",
        "avoid": ["Making every sentence a bullet", "Long bullets", "Repeated ideas", "Unnecessary sub-bullets"],
    },
    "before_after": {
        "id": "before_after",
        "name": "Before → After",
        "purpose": "Show a transformation by contrasting the situation before and after a change.",
        "structure": ["Hook", "Before", "Change", "After", "Lesson", "Closing"],
        "format": {
            "paragraphs": "short",
            "spacing": "generous",
            "bullets": False,
            "emojis": False,
            "formatting": "minimal",
        },
        "opening": "Highlight the transformation or contrast to create curiosity.",
        "body": "Clearly establish the starting point, explain what changed, then show the resulting state.",
        "ending": "Highlight the broader lesson or insight from the transformation.",
        "avoid": ["Fabricated results", "Unrealistic transformation", "Overstated claims", "Weak contrast"],
    },
    "minimalist": {
        "id": "minimalist",
        "name": "Minimalist",
        "purpose": "Deliver one powerful idea with maximum clarity and minimal words.",
        "structure": ["Hook", "Core Insight", "Supporting Thought", "Punchy Closing"],
        "format": {
            "paragraphs": "very_short",
            "spacing": "high",
            "bullets": False,
            "emojis": False,
            "formatting": "minimal",
        },
        "opening": "Start with a sharp, attention-grabbing statement.",
        "body": "Focus only on the essential idea and remove unnecessary context.",
        "ending": "End with a concise and memorable statement.",
        "avoid": ["Unnecessary explanation", "Long paragraphs", "Filler", "Excessive formatting"],
    },
    "ai_decides": {
        "id": "ai_decides",
        "name": "AI Decides",
        "purpose": "Let the writer choose the structure that best fits the topic and user's intent.",
        "structure": "AI-selected",
        "format": {
            "paragraphs": "AI-selected",
            "spacing": "natural",
            "bullets": "AI-selected",
            "emojis": "style-dependent",
            "formatting": "AI-selected",
        },
        "opening": "Choose the most effective hook for the topic.",
        "body": "Select the structure that best communicates the idea.",
        "ending": "Choose a natural and relevant closing.",
        "avoid": ["Forcing a template", "Unnecessary formatting", "Generic structure"],
    },
}
