name: Frontend CI

on:
  push:
    branches:
      - feat/analyser
    paths: 
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
   
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test -- -- watchALL=False
        continue-on-error:  true

      - name: Build Frontend
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: frontend

    

  
      
